apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-proyecto-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anth0ny-rdz/mi-proyecto
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mi-proyecto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true