apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
  namespace: mi-proyecto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-app  # Cambiar de "nginx" a "mi-app"
        image: python:3.9-alpine  # Cambiar nginx por Python
        ports:
        - containerPort: 5000  # Cambiar puerto 80 por 5000
        env:
        - name: LAUNCHDARKLY_SDK_KEY
          valueFrom:
            secretKeyRef:
              name: launchdarkly-secret
              key: sdk-key
        - name: LAUNCHDARKLY_ENV
          value: "production"
        command: ["python"]
        args: ["-m", "http.server", "5000"]  # Servidor simple para probar