apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
  namespace: mi-proyecto
spec:
  selector:
    app: mi-aplicacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP